// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/matrix.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMatrixInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -2054645180;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'crosschat_ffi',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiMatrixCreateDm({required String userId});

  Future<String> crateApiMatrixCreateGroup({
    required String name,
    required List<String> invites,
  });

  Future<String?> crateApiMatrixGetAccountData({required String eventType});

  Future<ChatMessage?> crateApiMatrixGetMessage({
    required String roomId,
    required String eventId,
  });

  Future<void> crateApiMatrixInitApp();

  Future<String> crateApiMatrixJoinRoom({required String roomIdOrAlias});

  Future<List<ChatRoom>> crateApiMatrixListRooms();

  Future<SessionInfo> crateApiMatrixLogin({
    required String homeserver,
    required String username,
    required String password,
    required String dataDir,
    required String deviceName,
  });

  Future<void> crateApiMatrixLogout();

  Future<String?> crateApiMatrixMarkRead({
    required String roomId,
    String? eventId,
  });

  Future<Uint8List> crateApiMatrixMediaBytes({
    required String source,
    int? thumbWidth,
    int? thumbHeight,
  });

  Future<List<String>> crateApiMatrixProbeHomeserver({required String url});

  Future<SessionInfo?> crateApiMatrixRestoreSession({required String dataDir});

  Future<List<ChatMessage>> crateApiMatrixRoomTimeline({
    required String roomId,
    required int limit,
  });

  Future<List<DirectoryUser>> crateApiMatrixSearchDirectory({
    required String term,
    required int limit,
  });

  Future<String> crateApiMatrixSendText({
    required String roomId,
    required String body,
    String? threadRoot,
  });

  Future<void> crateApiMatrixSetAccountData({
    required String eventType,
    required String json,
  });

  Future<void> crateApiMatrixSetMarkedUnread({
    required String roomId,
    required bool unread,
  });

  Future<bool> crateApiMatrixSetReaction({
    required String roomId,
    required String eventId,
    required String key,
    required bool add,
  });

  Stream<CoreUpdate> crateApiMatrixSubscribeUpdates();

  Future<void> crateApiMatrixSyncOnce();

  Future<List<ChatMessage>> crateApiMatrixThreadTimeline({
    required String roomId,
    required String rootId,
    required int limit,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiMatrixCreateDm({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixCreateDmConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixCreateDmConstMeta =>
      const TaskConstMeta(debugName: "create_dm", argNames: ["userId"]);

  @override
  Future<String> crateApiMatrixCreateGroup({
    required String name,
    required List<String> invites,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_list_String(invites, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixCreateGroupConstMeta,
        argValues: [name, invites],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixCreateGroupConstMeta => const TaskConstMeta(
    debugName: "create_group",
    argNames: ["name", "invites"],
  );

  @override
  Future<String?> crateApiMatrixGetAccountData({required String eventType}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(eventType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixGetAccountDataConstMeta,
        argValues: [eventType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetAccountDataConstMeta =>
      const TaskConstMeta(
        debugName: "get_account_data",
        argNames: ["eventType"],
      );

  @override
  Future<ChatMessage?> crateApiMatrixGetMessage({
    required String roomId,
    required String eventId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_chat_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixGetMessageConstMeta,
        argValues: [roomId, eventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetMessageConstMeta => const TaskConstMeta(
    debugName: "get_message",
    argNames: ["roomId", "eventId"],
  );

  @override
  Future<void> crateApiMatrixInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiMatrixJoinRoom({required String roomIdOrAlias}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomIdOrAlias, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixJoinRoomConstMeta,
        argValues: [roomIdOrAlias],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixJoinRoomConstMeta =>
      const TaskConstMeta(debugName: "join_room", argNames: ["roomIdOrAlias"]);

  @override
  Future<List<ChatRoom>> crateApiMatrixListRooms() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_room,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixListRoomsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixListRoomsConstMeta =>
      const TaskConstMeta(debugName: "list_rooms", argNames: []);

  @override
  Future<SessionInfo> crateApiMatrixLogin({
    required String homeserver,
    required String username,
    required String password,
    required String dataDir,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(dataDir, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixLoginConstMeta,
        argValues: [homeserver, username, password, dataDir, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLoginConstMeta => const TaskConstMeta(
    debugName: "login",
    argNames: ["homeserver", "username", "password", "dataDir", "deviceName"],
  );

  @override
  Future<void> crateApiMatrixLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<String?> crateApiMatrixMarkRead({
    required String roomId,
    String? eventId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_opt_String(eventId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixMarkReadConstMeta,
        argValues: [roomId, eventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMarkReadConstMeta => const TaskConstMeta(
    debugName: "mark_read",
    argNames: ["roomId", "eventId"],
  );

  @override
  Future<Uint8List> crateApiMatrixMediaBytes({
    required String source,
    int? thumbWidth,
    int? thumbHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_opt_box_autoadd_u_32(thumbWidth, serializer);
          sse_encode_opt_box_autoadd_u_32(thumbHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixMediaBytesConstMeta,
        argValues: [source, thumbWidth, thumbHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMediaBytesConstMeta => const TaskConstMeta(
    debugName: "media_bytes",
    argNames: ["source", "thumbWidth", "thumbHeight"],
  );

  @override
  Future<List<String>> crateApiMatrixProbeHomeserver({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixProbeHomeserverConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixProbeHomeserverConstMeta =>
      const TaskConstMeta(debugName: "probe_homeserver", argNames: ["url"]);

  @override
  Future<SessionInfo?> crateApiMatrixRestoreSession({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixRestoreSessionConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRestoreSessionConstMeta =>
      const TaskConstMeta(debugName: "restore_session", argNames: ["dataDir"]);

  @override
  Future<List<ChatMessage>> crateApiMatrixRoomTimeline({
    required String roomId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixRoomTimelineConstMeta,
        argValues: [roomId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRoomTimelineConstMeta => const TaskConstMeta(
    debugName: "room_timeline",
    argNames: ["roomId", "limit"],
  );

  @override
  Future<List<DirectoryUser>> crateApiMatrixSearchDirectory({
    required String term,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(term, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_directory_user,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixSearchDirectoryConstMeta,
        argValues: [term, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSearchDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "search_directory",
        argNames: ["term", "limit"],
      );

  @override
  Future<String> crateApiMatrixSendText({
    required String roomId,
    required String body,
    String? threadRoot,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(body, serializer);
          sse_encode_opt_String(threadRoot, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixSendTextConstMeta,
        argValues: [roomId, body, threadRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendTextConstMeta => const TaskConstMeta(
    debugName: "send_text",
    argNames: ["roomId", "body", "threadRoot"],
  );

  @override
  Future<void> crateApiMatrixSetAccountData({
    required String eventType,
    required String json,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(eventType, serializer);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixSetAccountDataConstMeta,
        argValues: [eventType, json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSetAccountDataConstMeta =>
      const TaskConstMeta(
        debugName: "set_account_data",
        argNames: ["eventType", "json"],
      );

  @override
  Future<void> crateApiMatrixSetMarkedUnread({
    required String roomId,
    required bool unread,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_bool(unread, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixSetMarkedUnreadConstMeta,
        argValues: [roomId, unread],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSetMarkedUnreadConstMeta =>
      const TaskConstMeta(
        debugName: "set_marked_unread",
        argNames: ["roomId", "unread"],
      );

  @override
  Future<bool> crateApiMatrixSetReaction({
    required String roomId,
    required String eventId,
    required String key,
    required bool add,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventId, serializer);
          sse_encode_String(key, serializer);
          sse_encode_bool(add, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixSetReactionConstMeta,
        argValues: [roomId, eventId, key, add],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSetReactionConstMeta => const TaskConstMeta(
    debugName: "set_reaction",
    argNames: ["roomId", "eventId", "key", "add"],
  );

  @override
  Stream<CoreUpdate> crateApiMatrixSubscribeUpdates() {
    final sink = RustStreamSink<CoreUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_core_update_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 20,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiMatrixSubscribeUpdatesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMatrixSubscribeUpdatesConstMeta =>
      const TaskConstMeta(debugName: "subscribe_updates", argNames: ["sink"]);

  @override
  Future<void> crateApiMatrixSyncOnce() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixSyncOnceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSyncOnceConstMeta =>
      const TaskConstMeta(debugName: "sync_once", argNames: []);

  @override
  Future<List<ChatMessage>> crateApiMatrixThreadTimeline({
    required String roomId,
    required String rootId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(rootId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMatrixThreadTimelineConstMeta,
        argValues: [roomId, rootId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixThreadTimelineConstMeta =>
      const TaskConstMeta(
        debugName: "thread_timeline",
        argNames: ["roomId", "rootId", "limit"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<CoreUpdate> dco_decode_StreamSink_core_update_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatMedia dco_decode_box_autoadd_chat_media(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_media(raw);
  }

  @protected
  ChatMessage dco_decode_box_autoadd_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_message(raw);
  }

  @protected
  ChatTapback dco_decode_box_autoadd_chat_tapback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_tapback(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  SessionInfo dco_decode_box_autoadd_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_info(raw);
  }

  @protected
  ThreadInfo dco_decode_box_autoadd_thread_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_thread_info(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ChatMedia dco_decode_chat_media(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ChatMedia(
      source: dco_decode_String(arr[0]),
      mimetype: dco_decode_opt_String(arr[1]),
      size: dco_decode_opt_box_autoadd_u_64(arr[2]),
      width: dco_decode_opt_box_autoadd_u_32(arr[3]),
      height: dco_decode_opt_box_autoadd_u_32(arr[4]),
      durationMs: dco_decode_opt_box_autoadd_u_64(arr[5]),
      filename: dco_decode_String(arr[6]),
      caption: dco_decode_opt_String(arr[7]),
      thumbnailSource: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return ChatMessage(
      eventId: dco_decode_String(arr[0]),
      sender: dco_decode_String(arr[1]),
      senderName: dco_decode_String(arr[2]),
      body: dco_decode_String(arr[3]),
      kind: dco_decode_String(arr[4]),
      ts: dco_decode_i_64(arr[5]),
      threadRoot: dco_decode_opt_String(arr[6]),
      inReplyTo: dco_decode_opt_String(arr[7]),
      thread: dco_decode_opt_box_autoadd_thread_info(arr[8]),
      edited: dco_decode_bool(arr[9]),
      isOwn: dco_decode_bool(arr[10]),
      senderAvatar: dco_decode_opt_String(arr[11]),
      media: dco_decode_opt_box_autoadd_chat_media(arr[12]),
      reactions: dco_decode_list_chat_reaction(arr[13]),
      tapback: dco_decode_opt_box_autoadd_chat_tapback(arr[14]),
    );
  }

  @protected
  ChatReaction dco_decode_chat_reaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChatReaction(
      key: dco_decode_String(arr[0]),
      senders: dco_decode_list_String(arr[1]),
      own: dco_decode_bool(arr[2]),
    );
  }

  @protected
  ChatRoom dco_decode_chat_room(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return ChatRoom(
      roomId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      topic: dco_decode_opt_String(arr[2]),
      isDm: dco_decode_bool(arr[3]),
      unread: dco_decode_u_64(arr[4]),
      highlights: dco_decode_u_64(arr[5]),
      lastTs: dco_decode_i_64(arr[6]),
      lastMessage: dco_decode_opt_String(arr[7]),
      networkId: dco_decode_opt_String(arr[8]),
      networkName: dco_decode_opt_String(arr[9]),
      threadsSupported: dco_decode_opt_box_autoadd_bool(arr[10]),
      bridgeId: dco_decode_opt_String(arr[11]),
      bridgeBot: dco_decode_opt_String(arr[12]),
      protocolId: dco_decode_opt_String(arr[13]),
      protocolName: dco_decode_opt_String(arr[14]),
      loginId: dco_decode_opt_String(arr[15]),
      roomType: dco_decode_opt_String(arr[16]),
      markedUnread: dco_decode_bool(arr[17]),
    );
  }

  @protected
  ChatTapback dco_decode_chat_tapback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChatTapback(
      key: dco_decode_String(arr[0]),
      removed: dco_decode_bool(arr[1]),
      targetText: dco_decode_opt_String(arr[2]),
      truncated: dco_decode_bool(arr[3]),
      targetKind: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  CoreUpdate dco_decode_core_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CoreUpdate(
      kind: dco_decode_String(arr[0]),
      roomId: dco_decode_opt_String(arr[1]),
      message: dco_decode_opt_box_autoadd_chat_message(arr[2]),
      state: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  DirectoryUser dco_decode_directory_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DirectoryUser(
      userId: dco_decode_String(arr[0]),
      displayName: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message).toList();
  }

  @protected
  List<ChatReaction> dco_decode_list_chat_reaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_reaction).toList();
  }

  @protected
  List<ChatRoom> dco_decode_list_chat_room(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_room).toList();
  }

  @protected
  List<DirectoryUser> dco_decode_list_directory_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_directory_user).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  ChatMedia? dco_decode_opt_box_autoadd_chat_media(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_chat_media(raw);
  }

  @protected
  ChatMessage? dco_decode_opt_box_autoadd_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_chat_message(raw);
  }

  @protected
  ChatTapback? dco_decode_opt_box_autoadd_chat_tapback(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_chat_tapback(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  SessionInfo? dco_decode_opt_box_autoadd_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_session_info(raw);
  }

  @protected
  ThreadInfo? dco_decode_opt_box_autoadd_thread_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_thread_info(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SessionInfo dco_decode_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SessionInfo(
      userId: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      homeserver: dco_decode_String(arr[2]),
      accessToken: dco_decode_String(arr[3]),
    );
  }

  @protected
  ThreadInfo dco_decode_thread_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ThreadInfo(
      replyCount: dco_decode_u_32(arr[0]),
      latestReplyTs: dco_decode_opt_box_autoadd_i_64(arr[1]),
      latestReplyBody: dco_decode_opt_String(arr[2]),
      participants: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<CoreUpdate> sse_decode_StreamSink_core_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  ChatMedia sse_decode_box_autoadd_chat_media(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_media(deserializer));
  }

  @protected
  ChatMessage sse_decode_box_autoadd_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_message(deserializer));
  }

  @protected
  ChatTapback sse_decode_box_autoadd_chat_tapback(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_tapback(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  SessionInfo sse_decode_box_autoadd_session_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_info(deserializer));
  }

  @protected
  ThreadInfo sse_decode_box_autoadd_thread_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_thread_info(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ChatMedia sse_decode_chat_media(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_source = sse_decode_String(deserializer);
    var var_mimetype = sse_decode_opt_String(deserializer);
    var var_size = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_filename = sse_decode_String(deserializer);
    var var_caption = sse_decode_opt_String(deserializer);
    var var_thumbnailSource = sse_decode_opt_String(deserializer);
    return ChatMedia(
      source: var_source,
      mimetype: var_mimetype,
      size: var_size,
      width: var_width,
      height: var_height,
      durationMs: var_durationMs,
      filename: var_filename,
      caption: var_caption,
      thumbnailSource: var_thumbnailSource,
    );
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_ts = sse_decode_i_64(deserializer);
    var var_threadRoot = sse_decode_opt_String(deserializer);
    var var_inReplyTo = sse_decode_opt_String(deserializer);
    var var_thread = sse_decode_opt_box_autoadd_thread_info(deserializer);
    var var_edited = sse_decode_bool(deserializer);
    var var_isOwn = sse_decode_bool(deserializer);
    var var_senderAvatar = sse_decode_opt_String(deserializer);
    var var_media = sse_decode_opt_box_autoadd_chat_media(deserializer);
    var var_reactions = sse_decode_list_chat_reaction(deserializer);
    var var_tapback = sse_decode_opt_box_autoadd_chat_tapback(deserializer);
    return ChatMessage(
      eventId: var_eventId,
      sender: var_sender,
      senderName: var_senderName,
      body: var_body,
      kind: var_kind,
      ts: var_ts,
      threadRoot: var_threadRoot,
      inReplyTo: var_inReplyTo,
      thread: var_thread,
      edited: var_edited,
      isOwn: var_isOwn,
      senderAvatar: var_senderAvatar,
      media: var_media,
      reactions: var_reactions,
      tapback: var_tapback,
    );
  }

  @protected
  ChatReaction sse_decode_chat_reaction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_senders = sse_decode_list_String(deserializer);
    var var_own = sse_decode_bool(deserializer);
    return ChatReaction(key: var_key, senders: var_senders, own: var_own);
  }

  @protected
  ChatRoom sse_decode_chat_room(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_topic = sse_decode_opt_String(deserializer);
    var var_isDm = sse_decode_bool(deserializer);
    var var_unread = sse_decode_u_64(deserializer);
    var var_highlights = sse_decode_u_64(deserializer);
    var var_lastTs = sse_decode_i_64(deserializer);
    var var_lastMessage = sse_decode_opt_String(deserializer);
    var var_networkId = sse_decode_opt_String(deserializer);
    var var_networkName = sse_decode_opt_String(deserializer);
    var var_threadsSupported = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_bridgeId = sse_decode_opt_String(deserializer);
    var var_bridgeBot = sse_decode_opt_String(deserializer);
    var var_protocolId = sse_decode_opt_String(deserializer);
    var var_protocolName = sse_decode_opt_String(deserializer);
    var var_loginId = sse_decode_opt_String(deserializer);
    var var_roomType = sse_decode_opt_String(deserializer);
    var var_markedUnread = sse_decode_bool(deserializer);
    return ChatRoom(
      roomId: var_roomId,
      name: var_name,
      topic: var_topic,
      isDm: var_isDm,
      unread: var_unread,
      highlights: var_highlights,
      lastTs: var_lastTs,
      lastMessage: var_lastMessage,
      networkId: var_networkId,
      networkName: var_networkName,
      threadsSupported: var_threadsSupported,
      bridgeId: var_bridgeId,
      bridgeBot: var_bridgeBot,
      protocolId: var_protocolId,
      protocolName: var_protocolName,
      loginId: var_loginId,
      roomType: var_roomType,
      markedUnread: var_markedUnread,
    );
  }

  @protected
  ChatTapback sse_decode_chat_tapback(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_removed = sse_decode_bool(deserializer);
    var var_targetText = sse_decode_opt_String(deserializer);
    var var_truncated = sse_decode_bool(deserializer);
    var var_targetKind = sse_decode_opt_String(deserializer);
    return ChatTapback(
      key: var_key,
      removed: var_removed,
      targetText: var_targetText,
      truncated: var_truncated,
      targetKind: var_targetKind,
    );
  }

  @protected
  CoreUpdate sse_decode_core_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_roomId = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_opt_box_autoadd_chat_message(deserializer);
    var var_state = sse_decode_opt_String(deserializer);
    return CoreUpdate(
      kind: var_kind,
      roomId: var_roomId,
      message: var_message,
      state: var_state,
    );
  }

  @protected
  DirectoryUser sse_decode_directory_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_opt_String(deserializer);
    return DirectoryUser(userId: var_userId, displayName: var_displayName);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatReaction> sse_decode_list_chat_reaction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatReaction>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_reaction(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatRoom> sse_decode_list_chat_room(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatRoom>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_room(deserializer));
    }
    return ans_;
  }

  @protected
  List<DirectoryUser> sse_decode_list_directory_user(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DirectoryUser>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_directory_user(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ChatMedia? sse_decode_opt_box_autoadd_chat_media(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_chat_media(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ChatMessage? sse_decode_opt_box_autoadd_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_chat_message(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ChatTapback? sse_decode_opt_box_autoadd_chat_tapback(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_chat_tapback(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionInfo? sse_decode_opt_box_autoadd_session_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_session_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ThreadInfo? sse_decode_opt_box_autoadd_thread_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_thread_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_homeserver = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    return SessionInfo(
      userId: var_userId,
      deviceId: var_deviceId,
      homeserver: var_homeserver,
      accessToken: var_accessToken,
    );
  }

  @protected
  ThreadInfo sse_decode_thread_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_replyCount = sse_decode_u_32(deserializer);
    var var_latestReplyTs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_latestReplyBody = sse_decode_opt_String(deserializer);
    var var_participants = sse_decode_list_String(deserializer);
    return ThreadInfo(
      replyCount: var_replyCount,
      latestReplyTs: var_latestReplyTs,
      latestReplyBody: var_latestReplyBody,
      participants: var_participants,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_core_update_Sse(
    RustStreamSink<CoreUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_core_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chat_media(
    ChatMedia self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_media(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chat_message(
    ChatMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chat_tapback(
    ChatTapback self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_tapback(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_session_info(
    SessionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_thread_info(
    ThreadInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_thread_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_chat_media(ChatMedia self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.source, serializer);
    sse_encode_opt_String(self.mimetype, serializer);
    sse_encode_opt_box_autoadd_u_64(self.size, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMs, serializer);
    sse_encode_String(self.filename, serializer);
    sse_encode_opt_String(self.caption, serializer);
    sse_encode_opt_String(self.thumbnailSource, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventId, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_i_64(self.ts, serializer);
    sse_encode_opt_String(self.threadRoot, serializer);
    sse_encode_opt_String(self.inReplyTo, serializer);
    sse_encode_opt_box_autoadd_thread_info(self.thread, serializer);
    sse_encode_bool(self.edited, serializer);
    sse_encode_bool(self.isOwn, serializer);
    sse_encode_opt_String(self.senderAvatar, serializer);
    sse_encode_opt_box_autoadd_chat_media(self.media, serializer);
    sse_encode_list_chat_reaction(self.reactions, serializer);
    sse_encode_opt_box_autoadd_chat_tapback(self.tapback, serializer);
  }

  @protected
  void sse_encode_chat_reaction(ChatReaction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_list_String(self.senders, serializer);
    sse_encode_bool(self.own, serializer);
  }

  @protected
  void sse_encode_chat_room(ChatRoom self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.topic, serializer);
    sse_encode_bool(self.isDm, serializer);
    sse_encode_u_64(self.unread, serializer);
    sse_encode_u_64(self.highlights, serializer);
    sse_encode_i_64(self.lastTs, serializer);
    sse_encode_opt_String(self.lastMessage, serializer);
    sse_encode_opt_String(self.networkId, serializer);
    sse_encode_opt_String(self.networkName, serializer);
    sse_encode_opt_box_autoadd_bool(self.threadsSupported, serializer);
    sse_encode_opt_String(self.bridgeId, serializer);
    sse_encode_opt_String(self.bridgeBot, serializer);
    sse_encode_opt_String(self.protocolId, serializer);
    sse_encode_opt_String(self.protocolName, serializer);
    sse_encode_opt_String(self.loginId, serializer);
    sse_encode_opt_String(self.roomType, serializer);
    sse_encode_bool(self.markedUnread, serializer);
  }

  @protected
  void sse_encode_chat_tapback(ChatTapback self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_bool(self.removed, serializer);
    sse_encode_opt_String(self.targetText, serializer);
    sse_encode_bool(self.truncated, serializer);
    sse_encode_opt_String(self.targetKind, serializer);
  }

  @protected
  void sse_encode_core_update(CoreUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.roomId, serializer);
    sse_encode_opt_box_autoadd_chat_message(self.message, serializer);
    sse_encode_opt_String(self.state, serializer);
  }

  @protected
  void sse_encode_directory_user(DirectoryUser self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_opt_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_reaction(
    List<ChatReaction> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_reaction(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_room(
    List<ChatRoom> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_room(item, serializer);
    }
  }

  @protected
  void sse_encode_list_directory_user(
    List<DirectoryUser> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_directory_user(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_chat_media(
    ChatMedia? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_chat_media(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_chat_message(
    ChatMessage? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_chat_message(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_chat_tapback(
    ChatTapback? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_chat_tapback(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_session_info(
    SessionInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_session_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_thread_info(
    ThreadInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_thread_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.homeserver, serializer);
    sse_encode_String(self.accessToken, serializer);
  }

  @protected
  void sse_encode_thread_info(ThreadInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.replyCount, serializer);
    sse_encode_opt_box_autoadd_i_64(self.latestReplyTs, serializer);
    sse_encode_opt_String(self.latestReplyBody, serializer);
    sse_encode_list_String(self.participants, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
