//! Homeserver integration.
//!
//! * External homeservers: registrations are written to a directory
//!   (Tuwunel `appservice_dir`) or left for the admin with instructions
//!   (Synapse `app_service_config_files` + restart, Continuwuity admin room).
//! * Bundled homeserver: crosschatd writes a Tuwunel config and runs it as a
//!   supervised child process. It runs as a separate process, never linked
//!   in, for crash isolation and a clean license boundary.

use crate::config::{BundledConfig, Config, RegistrationMode};
use crate::supervisor::ProcessSpec;
use anyhow::Result;
use std::path::Path;
use std::time::Duration;

fn toml_str(s: &str) -> String {
    toml::Value::String(s.to_string()).to_string()
}

/// Render `tuwunel.toml` for the bundled homeserver.
pub fn tuwunel_config(cfg: &Config, b: &BundledConfig, registration_token: &str) -> String {
    let db = cfg.data_dir.join("homeserver/db");
    let federation = b.federation.unwrap_or(false);
    let mut out = String::new();
    out.push_str("# Generated by crosschatd. Edits will be overwritten.\n[global]\n");
    out.push_str(&format!(
        "server_name = {}\n",
        toml_str(&cfg.homeserver.server_name)
    ));
    out.push_str(&format!(
        "database_path = {}\n",
        toml_str(&db.display().to_string())
    ));
    out.push_str("address = [\"127.0.0.1\"]\n");
    out.push_str(&format!("port = {}\n", b.port));
    out.push_str(&format!("allow_federation = {federation}\n"));
    out.push_str(&format!("allow_registration = {}\n", b.allow_registration));
    out.push_str(&format!(
        "registration_token = {}\n",
        toml_str(registration_token)
    ));
    out.push_str("new_user_displayname_suffix = \"\"\n");
    if !federation {
        out.push_str("trusted_servers = []\n");
    }
    out.push_str(&format!(
        "appservice_dir = {}\n",
        toml_str(&cfg.registrations_dir().display().to_string())
    ));
    out
}

pub fn tuwunel_spec(cfg: &Config, b: &BundledConfig) -> ProcessSpec {
    let dir = cfg.data_dir.join("homeserver");
    ProcessSpec {
        name: "homeserver".into(),
        program: b.binary.clone(),
        args: vec!["-c".into(), dir.join("tuwunel.toml").display().to_string()],
        env: vec![],
        cwd: Some(dir.clone()),
        log_file: Some(dir.join("homeserver.log")),
    }
}

pub fn prepare_bundled(
    cfg: &Config,
    b: &BundledConfig,
    registration_token: &str,
) -> Result<ProcessSpec> {
    let dir = cfg.data_dir.join("homeserver");
    std::fs::create_dir_all(dir.join("db"))?;
    crate::secrets::write_private(
        &dir.join("tuwunel.toml"),
        tuwunel_config(cfg, b, registration_token).as_bytes(),
    )?;
    Ok(tuwunel_spec(cfg, b))
}

/// Poll `/_matrix/client/versions` until the homeserver answers.
pub async fn wait_ready(http: &reqwest::Client, url: &str, timeout: Duration) -> bool {
    let deadline = tokio::time::Instant::now() + timeout;
    let versions = format!("{}/_matrix/client/versions", url.trim_end_matches('/'));
    while tokio::time::Instant::now() < deadline {
        if let Ok(r) = http
            .get(&versions)
            .timeout(Duration::from_secs(2))
            .send()
            .await
            && r.status().is_success()
        {
            return true;
        }
        tokio::time::sleep(Duration::from_millis(500)).await;
    }
    false
}

/// Human instructions for manual registration mode.
pub fn manual_instructions(cfg: &Config, reg_files: &[&Path]) -> String {
    let files: Vec<String> = reg_files
        .iter()
        .map(|p| format!("  - {}", p.display()))
        .collect();
    match &cfg.homeserver.registration {
        RegistrationMode::Directory { path } => {
            format!(
                "Registrations written to {} (homeserver appservice_dir). Restart the homeserver to load new bridges.",
                path.display()
            )
        }
        RegistrationMode::Manual => format!(
            "Register these appservices with your homeserver:\n{}\n\
             Synapse: add them to `app_service_config_files` in homeserver.yaml and restart.\n\
             Tuwunel: set `appservice_dir` to {} (or use the directory registration mode).\n\
             Continuwuity/Conduit: send `!admin appservices register` with the YAML in the admin room.",
            files.join("\n"),
            cfg.registrations_dir().display()
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tuwunel_config_reflects_federation_choice() {
        let mut cfg = Config::from_toml(Config::example()).unwrap();
        let b = BundledConfig {
            implementation: "tuwunel".into(),
            binary: "/usr/bin/tuwunel".into(),
            port: 6167,
            federation: Some(false),
            allow_registration: true,
        };
        cfg.homeserver.bundled = Some(b.clone());
        let t = tuwunel_config(&cfg, &b, "tok\"en");
        let parsed: toml::Table = toml::from_str(&t).unwrap();
        let g = parsed["global"].as_table().unwrap();
        assert_eq!(g["allow_federation"].as_bool(), Some(false));
        assert_eq!(g["server_name"].as_str(), Some("example.com"));
        assert_eq!(g["registration_token"].as_str(), Some("tok\"en"));
        assert_eq!(
            g["address"].as_array().unwrap()[0].as_str(),
            Some("127.0.0.1")
        );
        assert!(
            g["appservice_dir"]
                .as_str()
                .unwrap()
                .ends_with("registrations")
        );
        let fed = BundledConfig {
            federation: Some(true),
            ..b
        };
        let parsed: toml::Table = toml::from_str(&tuwunel_config(&cfg, &fed, "t")).unwrap();
        assert_eq!(parsed["global"]["allow_federation"].as_bool(), Some(true));
        assert!(parsed["global"].get("trusted_servers").is_none());
    }
}
