//! Local mode: `crosschatd local --dir <dir>`.
//!
//! What the desktop app starts when you pick "Start a new server on this
//! computer". One directory holds everything:
//!
//! ```text
//! <dir>/crosschatd.toml   generated once (server_name = "localhost", bundled
//!                         Tuwunel on 127.0.0.1, federation off); editable
//! <dir>/local.json        the owner account, once created
//! <dir>/crosschatd.log    daemon log (the app starts us detached)
//! <dir>/crosschatd.pid    pid of the running daemon
//! <dir>/data/             daemon data: vault, admin.token, homeserver db,
//!                         bridges, registrations, manifests
//! ```
//!
//! Unlike `run`, the HTTP API binds *before* setup so the app can show
//! progress (`GET /_crosschat/v1/local/status`) while Tuwunel is downloaded
//! or built and bridges are installed. Other API routes answer 503 until
//! setup finishes. The owner account is created once with
//! `POST /_crosschat/v1/local/owner` (needs the local admin token from
//! `data/admin.token`), which registers it on Tuwunel with the vault's
//! registration token. Tuwunel makes the first account a server admin.

use crate::api::ApiError;
use crate::auth::{bearer, secret_eq};
use crate::config::Config;
use crate::daemon::Daemon;
use crate::secrets::{Vault, write_private};
use anyhow::{Context, Result, bail};
use axum::{
    Json, Router,
    body::Body,
    extract::{Request, State},
    http::{HeaderMap, StatusCode},
    response::{IntoResponse, Response},
    routing::{get, post},
};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock, RwLock};
use std::time::Duration;
use tower::ServiceExt;
use tracing::{error, info};

pub const SERVER_NAME: &str = "localhost";
pub const DEFAULT_LISTEN: &str = "127.0.0.1:29300";
pub const DEFAULT_HS_PORT: u16 = 6167;
pub const DEFAULT_BRIDGES: &[&str] = &["gmessages", "slack"];

/// Bridge manifests compiled into the binary; local mode writes them to
/// `data/manifests` on every start so they always match this crosschatd.
pub const EMBEDDED_MANIFESTS: &[(&str, &str)] = &[
    (
        "gmessages.yaml",
        include_str!("../../../manifests/gmessages.yaml"),
    ),
    (
        "groupme.yaml",
        include_str!("../../../manifests/groupme.yaml"),
    ),
    (
        "imessage.yaml",
        include_str!("../../../manifests/imessage.yaml"),
    ),
    ("slack.yaml", include_str!("../../../manifests/slack.yaml")),
];

/// Files inside a local-mode directory.
#[derive(Debug, Clone)]
pub struct LocalPaths {
    pub root: PathBuf,
}

impl LocalPaths {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }
    pub fn config(&self) -> PathBuf {
        self.root.join("crosschatd.toml")
    }
    pub fn state(&self) -> PathBuf {
        self.root.join("local.json")
    }
    pub fn pid(&self) -> PathBuf {
        self.root.join("crosschatd.pid")
    }
    pub fn log(&self) -> PathBuf {
        self.root.join("crosschatd.log")
    }
    pub fn data(&self) -> PathBuf {
        self.root.join("data")
    }
    pub fn manifests(&self) -> PathBuf {
        self.data().join("manifests")
    }
}

/// Options used when generating `crosschatd.toml` for the first time.
#[derive(Debug, Clone)]
pub struct LocalOptions {
    pub listen: SocketAddr,
    pub hs_port: u16,
    pub bridges: Vec<String>,
}

impl Default for LocalOptions {
    fn default() -> Self {
        Self {
            listen: DEFAULT_LISTEN.parse().unwrap(),
            hs_port: DEFAULT_HS_PORT,
            bridges: DEFAULT_BRIDGES.iter().map(|s| s.to_string()).collect(),
        }
    }
}

/// The generated `crosschatd.toml`.
pub fn default_config_toml(o: &LocalOptions) -> String {
    let mut s = format!(
        r#"# Crosschat local server, generated by `crosschatd local`. Safe to edit
# (e.g. to enable more bridges); restart Crosschat afterwards.
#
# server_name is permanent. This server is for this computer only: no
# federation, and phones can't reach it. Moving to a real domain later is a
# migration (re-backfill), not a rename.
listen = "{listen}"
data_dir = "data"
# Refreshed from the crosschatd binary on every start.
manifests_dir = "data/manifests"

[homeserver]
url = "http://127.0.0.1:{hs}"
server_name = "{SERVER_NAME}"
registration = {{ kind = "manual" }}

[homeserver.bundled]
implementation = "tuwunel"
# binary = "/path/to/tuwunel"  # default: $TUWUNEL_BIN, next to crosschatd, or the pinned build in the cache
port = {hs}
federation = false
# Registration requires the random token in data/vault.json (owner bootstrap).
allow_registration = true

[auth]
# The owner from local.json is added automatically.
admins = []
"#,
        listen = o.listen,
        hs = o.hs_port,
    );
    for id in ["gmessages", "slack", "imessage", "groupme"] {
        let on = o.bridges.iter().any(|b| b == id);
        s.push_str(&format!("\n[bridges.{id}]\nenabled = {on}\n"));
    }
    s
}

/// `local.json`.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct LocalState {
    #[serde(default)]
    pub owner: Option<String>,
    #[serde(default)]
    pub created_at_ms: Option<u64>,
}

impl LocalState {
    pub fn load(path: &Path) -> Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }
        serde_json::from_slice(&std::fs::read(path)?)
            .with_context(|| format!("parsing {}", path.display()))
    }
    pub fn save(&self, path: &Path) -> Result<()> {
        write_private(path, &serde_json::to_vec_pretty(self)?)
    }
}

pub fn write_embedded_manifests(dir: &Path) -> Result<()> {
    std::fs::create_dir_all(dir)?;
    for (name, text) in EMBEDDED_MANIFESTS {
        std::fs::write(dir.join(name), text)?;
    }
    Ok(())
}

/// Matrix localpart rules (`[a-z0-9._=/-]+`), as entered in the setup form.
pub fn validate_localpart(s: &str) -> Result<(), String> {
    if s.is_empty() {
        return Err("Pick a username.".into());
    }
    if s.len() > 64 {
        return Err("Username is too long (64 characters max).".into());
    }
    if !s
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || "._=/-".contains(c))
    {
        return Err("Use lowercase letters, digits and . _ = / - only.".into());
    }
    Ok(())
}

pub fn validate_password(p: &str) -> Result<(), String> {
    if p.chars().count() < 8 {
        return Err("Use at least 8 characters for the password.".into());
    }
    Ok(())
}

/// Create the directory layout and config, and load it. The owner from
/// `local.json` becomes an admin.
pub fn prepare(paths: &LocalPaths, opts: &LocalOptions) -> Result<Config> {
    std::fs::create_dir_all(paths.data())
        .with_context(|| format!("creating {}", paths.data().display()))?;
    if !paths.config().exists() {
        std::fs::write(paths.config(), default_config_toml(opts))?;
    }
    write_embedded_manifests(&paths.manifests())?;
    let mut cfg = Config::load(&paths.config())?;
    let Some(b) = &cfg.homeserver.bundled else {
        bail!(
            "{} has no [homeserver.bundled]; local mode always runs its own homeserver",
            paths.config().display()
        );
    };
    if b.federation != Some(false) {
        bail!("local mode is for this computer only; set federation = false");
    }
    if let Some(owner) = LocalState::load(&paths.state())?.owner
        && !cfg.auth.admins.contains(&owner)
    {
        cfg.auth.admins.push(owner);
    }
    Ok(cfg)
}

#[derive(Debug, Clone, Serialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Phase {
    Starting,
    Ready,
    Failed,
}

#[derive(Debug, Clone, Serialize)]
pub struct Status {
    pub phase: Phase,
    pub detail: String,
    pub error: Option<String>,
}

/// Shared state of a running local-mode daemon.
pub struct LocalServer {
    pub paths: LocalPaths,
    pub cfg: Config,
    pub admin_token: String,
    pub http: reqwest::Client,
    status: RwLock<Status>,
    owner: RwLock<Option<String>>,
    daemon: OnceLock<Arc<Daemon>>,
    api: OnceLock<Router>,
    owner_lock: tokio::sync::Mutex<()>,
    /// Modification time of our executable when we started: the app compares
    /// it with the crosschatd it ships and restarts us after an update.
    exe_mtime_ms: Option<u64>,
}

/// mtime of the running executable, in ms since the epoch.
pub fn exe_mtime_ms() -> Option<u64> {
    let exe = std::env::current_exe().ok()?;
    let t = std::fs::metadata(exe).ok()?.modified().ok()?;
    t.duration_since(std::time::UNIX_EPOCH)
        .ok()
        .map(|d| d.as_millis() as u64)
}

impl LocalServer {
    pub fn new(paths: LocalPaths, cfg: Config) -> Result<Arc<Self>> {
        let mut vault = Vault::open(cfg.data_dir.join("vault.json"))?;
        let admin_token = vault.admin_token()?;
        write_private(
            &crate::daemon::admin_token_path(&cfg),
            admin_token.as_bytes(),
        )?;
        let owner = LocalState::load(&paths.state())?.owner;
        Ok(Arc::new(Self {
            paths,
            cfg,
            admin_token,
            http: reqwest::Client::builder()
                .user_agent(concat!("crosschatd/", env!("CARGO_PKG_VERSION")))
                .build()?,
            status: RwLock::new(Status {
                phase: Phase::Starting,
                detail: "Starting".into(),
                error: None,
            }),
            owner: RwLock::new(owner),
            daemon: OnceLock::new(),
            api: OnceLock::new(),
            owner_lock: Default::default(),
            exe_mtime_ms: exe_mtime_ms(),
        }))
    }

    pub fn status(&self) -> Status {
        self.status.read().unwrap().clone()
    }

    pub fn set_detail(&self, detail: String) {
        let mut s = self.status.write().unwrap();
        if s.phase == Phase::Starting {
            s.detail = detail;
        }
    }

    pub fn owner(&self) -> Option<String> {
        self.owner.read().unwrap().clone()
    }

    pub fn daemon(&self) -> Option<&Arc<Daemon>> {
        self.daemon.get()
    }

    /// Mark the daemon ready and start routing the regular API to it.
    pub fn set_ready(&self, d: Arc<Daemon>) {
        if let Some(o) = self.owner() {
            d.add_admin(&o);
        }
        let _ = self.api.set(crate::api::router(d.clone()));
        let _ = self.daemon.set(d);
        *self.status.write().unwrap() = Status {
            phase: Phase::Ready,
            detail: "Ready".into(),
            error: None,
        };
    }

    pub fn set_failed(&self, error: String) {
        let mut s = self.status.write().unwrap();
        s.phase = Phase::Failed;
        s.error = Some(error);
    }

    /// Run the full daemon setup in the background, updating the status.
    pub async fn setup(self: &Arc<Self>) {
        let me = self.clone();
        let progress: crate::tuwunel::Progress = Arc::new(move |d| me.set_detail(d));
        match Daemon::setup_with_progress(self.cfg.clone(), progress, Some(self.paths.config()))
            .await
        {
            Ok(d) => {
                if crate::homeserver::wait_ready(
                    &self.http,
                    &self.cfg.homeserver.url,
                    Duration::from_secs(5),
                )
                .await
                {
                    info!("local server ready");
                    self.set_ready(d);
                } else {
                    let log = self.cfg.data_dir.join("homeserver/homeserver.log");
                    self.set_failed(format!(
                        "The Matrix server didn't start. Log: {}",
                        log.display()
                    ));
                    // Keep the daemon so shutdown stops what did start.
                    let _ = self.daemon.set(d);
                }
            }
            Err(e) => {
                error!("local setup failed: {e:#}");
                self.set_failed(format!("{e:#}"));
            }
        }
    }

    fn status_json(&self) -> Value {
        let s = self.status();
        json!({
            "mode": "local",
            "version": env!("CARGO_PKG_VERSION"),
            "phase": s.phase,
            "detail": s.detail,
            "error": s.error,
            "server_name": self.cfg.homeserver.server_name,
            "federation": false,
            "homeserver_url": self.cfg.homeserver.url,
            "daemon_url": format!("http://{}", self.cfg.listen),
            "data_dir": self.paths.root,
            "owner": self.owner(),
            "exe": std::env::current_exe().ok(),
            "exe_mtime_ms": self.exe_mtime_ms,
        })
    }

    /// Create the owner account (once).
    pub async fn create_owner(&self, username: &str, password: &str) -> Result<String, ApiError> {
        let _guard = self.owner_lock.lock().await;
        if self.owner().is_some() {
            return Err(ApiError(
                StatusCode::CONFLICT,
                "CC_OWNER_EXISTS",
                "this server already has an owner".into(),
            ));
        }
        let Some(d) = self.daemon() else {
            return Err(ApiError(
                StatusCode::SERVICE_UNAVAILABLE,
                "CC_STARTING",
                "the local server is still starting".into(),
            ));
        };
        let username = username.trim().trim_start_matches('@').to_lowercase();
        validate_localpart(&username)
            .map_err(|e| ApiError(StatusCode::BAD_REQUEST, "M_INVALID_USERNAME", e))?;
        validate_password(password)
            .map_err(|e| ApiError(StatusCode::BAD_REQUEST, "M_WEAK_PASSWORD", e))?;
        let token = Vault::open(self.cfg.data_dir.join("vault.json"))
            .ok()
            .and_then(|v| v.data.hs_registration_token)
            .ok_or_else(|| {
                ApiError(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "CC_NO_TOKEN",
                    "registration token missing from the vault".into(),
                )
            })?;
        let user_id = register_with_token(
            &self.http,
            &self.cfg.homeserver.url,
            &token,
            &username,
            password,
        )
        .await?;
        let state = LocalState {
            owner: Some(user_id.clone()),
            created_at_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .ok()
                .map(|d| d.as_millis() as u64),
        };
        state.save(&self.paths.state()).map_err(|e| {
            ApiError(
                StatusCode::INTERNAL_SERVER_ERROR,
                "CC_STATE",
                format!("saving local.json: {e:#}"),
            )
        })?;
        d.add_admin(&user_id);
        *self.owner.write().unwrap() = Some(user_id.clone());
        info!(%user_id, "owner account created");
        Ok(user_id)
    }
}

/// Register an account through the client-server API's user-interactive
/// auth with an `m.login.registration_token` stage (plus `m.login.dummy` if
/// the server asks for it). Returns the new user ID.
pub async fn register_with_token(
    http: &reqwest::Client,
    hs_url: &str,
    token: &str,
    username: &str,
    password: &str,
) -> Result<String, ApiError> {
    let url = format!(
        "{}/_matrix/client/v3/register",
        hs_url.trim_end_matches('/')
    );
    let upstream = |e: reqwest::Error| {
        ApiError(
            StatusCode::BAD_GATEWAY,
            "CC_HOMESERVER_UNREACHABLE",
            e.to_string(),
        )
    };
    let mut body = json!({
        "username": username,
        "password": password,
        "inhibit_login": true,
        "initial_device_display_name": "crosschatd setup",
    });
    let mut session: Option<String> = None;
    let mut done: Vec<String> = Vec::new();
    for _ in 0..4 {
        let resp = http
            .post(&url)
            .json(&body)
            .timeout(Duration::from_secs(30))
            .send()
            .await
            .map_err(upstream)?;
        let status = resp.status();
        let v: Value = resp.json().await.unwrap_or(Value::Null);
        if status.is_success() {
            return v
                .get("user_id")
                .and_then(Value::as_str)
                .map(str::to_owned)
                .ok_or_else(|| {
                    ApiError(
                        StatusCode::BAD_GATEWAY,
                        "CC_BAD_RESPONSE",
                        "register response had no user_id".into(),
                    )
                });
        }
        let errcode = v.get("errcode").and_then(Value::as_str).unwrap_or("");
        let msg = v
            .get("error")
            .and_then(Value::as_str)
            .unwrap_or("registration failed")
            .to_string();
        if status != reqwest::StatusCode::UNAUTHORIZED || v.get("flows").is_none() {
            let code = match errcode {
                "M_USER_IN_USE" => StatusCode::CONFLICT,
                "M_INVALID_USERNAME" | "M_WEAK_PASSWORD" | "M_EXCLUSIVE" => StatusCode::BAD_REQUEST,
                _ => StatusCode::BAD_GATEWAY,
            };
            let errcode: &'static str = match errcode {
                "M_USER_IN_USE" => "M_USER_IN_USE",
                "M_INVALID_USERNAME" => "M_INVALID_USERNAME",
                "M_WEAK_PASSWORD" => "M_WEAK_PASSWORD",
                "M_EXCLUSIVE" => "M_EXCLUSIVE",
                _ => "CC_REGISTER_FAILED",
            };
            return Err(ApiError(code, errcode, msg));
        }
        // 401 + UIA: pick the next stage.
        if let Some(s) = v.get("session").and_then(Value::as_str) {
            session = Some(s.to_string());
        }
        if let Some(c) = v.get("completed").and_then(Value::as_array) {
            done = c
                .iter()
                .filter_map(|x| x.as_str().map(str::to_owned))
                .collect();
        }
        let next = if !done.iter().any(|s| s == "m.login.registration_token") {
            json!({"type": "m.login.registration_token", "token": token, "session": session})
        } else {
            json!({"type": "m.login.dummy", "session": session})
        };
        if body.get("auth") == Some(&next) {
            return Err(ApiError(
                StatusCode::BAD_GATEWAY,
                "CC_REGISTER_FAILED",
                format!("homeserver rejected the registration token: {msg}"),
            ));
        }
        body["auth"] = next;
    }
    Err(ApiError(
        StatusCode::BAD_GATEWAY,
        "CC_REGISTER_FAILED",
        "registration did not complete".into(),
    ))
}

type LocalState_ = Arc<LocalServer>;

pub fn router(local: Arc<LocalServer>) -> Router {
    Router::new()
        .route("/_crosschat/v1/health", get(health))
        .route("/_crosschat/v1/local/status", get(status))
        .route("/_crosschat/v1/local/owner", post(owner))
        .fallback(fallback)
        .with_state(local)
}

async fn health(State(l): State<LocalState_>) -> Json<Value> {
    Json(json!({
        "status": "ok",
        "version": env!("CARGO_PKG_VERSION"),
        "mode": "local",
        "phase": l.status().phase,
    }))
}

async fn status(State(l): State<LocalState_>) -> Json<Value> {
    Json(l.status_json())
}

#[derive(Deserialize)]
struct OwnerBody {
    username: String,
    password: String,
}

async fn owner(
    State(l): State<LocalState_>,
    headers: HeaderMap,
    Json(b): Json<OwnerBody>,
) -> Result<Json<Value>, ApiError> {
    if !bearer(&headers).is_some_and(|t| secret_eq(t, &l.admin_token)) {
        return Err(ApiError(
            StatusCode::UNAUTHORIZED,
            "M_UNKNOWN_TOKEN",
            "the local admin token (data/admin.token) is required".into(),
        ));
    }
    let user_id = l.create_owner(&b.username, &b.password).await?;
    Ok(Json(json!({
        "user_id": user_id,
        "homeserver_url": l.cfg.homeserver.url,
    })))
}

async fn fallback(State(l): State<LocalState_>, req: Request<Body>) -> Response {
    match l.api.get() {
        Some(api) => match api.clone().oneshot(req).await {
            Ok(r) => r,
            Err(e) => match e {},
        },
        None => {
            let s = l.status();
            let (code, msg) = match s.phase {
                Phase::Failed => (
                    "CC_SETUP_FAILED",
                    s.error.unwrap_or_else(|| "setup failed".into()),
                ),
                _ => ("CC_STARTING", s.detail),
            };
            (
                StatusCode::SERVICE_UNAVAILABLE,
                Json(json!({"errcode": code, "error": msg})),
            )
                .into_response()
        }
    }
}

/// Wait for SIGINT or SIGTERM (the app stops us with SIGTERM).
pub async fn shutdown_signal() {
    #[cfg(unix)]
    {
        use tokio::signal::unix::{SignalKind, signal};
        let mut term = signal(SignalKind::terminate()).expect("SIGTERM handler");
        tokio::select! {
            _ = tokio::signal::ctrl_c() => {}
            _ = term.recv() => {}
        }
    }
    #[cfg(not(unix))]
    {
        let _ = tokio::signal::ctrl_c().await;
    }
}

/// `crosschatd local`: bind, report progress, set up, serve until signalled.
pub async fn run(paths: LocalPaths, opts: LocalOptions) -> Result<()> {
    let cfg = prepare(&paths, &opts)?;
    let listen = cfg.listen;
    let listener = tokio::net::TcpListener::bind(listen)
        .await
        .with_context(|| {
            format!("binding {listen} (is another Crosschat server already running?)")
        })?;
    std::fs::write(paths.pid(), std::process::id().to_string())?;
    let local = LocalServer::new(paths.clone(), cfg)?;
    info!(
        dir = %paths.root.display(),
        "crosschatd local mode on http://{listen}/_crosschat/v1/local/status"
    );
    let setup = {
        let l = local.clone();
        tokio::spawn(async move { l.setup().await })
    };
    let result = axum::serve(listener, router(local.clone()))
        .with_graceful_shutdown(shutdown_signal())
        .await;
    info!("shutting down");
    setup.abort();
    if let Some(d) = local.daemon() {
        d.shutdown().await;
    }
    let _ = std::fs::remove_file(paths.pid());
    result?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;

    #[test]
    fn default_config_is_localhost_private_and_valid() {
        let dir = tempfile::tempdir().unwrap();
        let paths = LocalPaths::new(dir.path());
        let cfg = prepare(&paths, &LocalOptions::default()).unwrap();
        assert_eq!(cfg.homeserver.server_name, "localhost");
        assert_eq!(cfg.homeserver.url, "http://127.0.0.1:6167");
        assert_eq!(cfg.listen.to_string(), "127.0.0.1:29300");
        let b = cfg.homeserver.bundled.as_ref().unwrap();
        assert_eq!(b.federation, Some(false));
        assert!(b.allow_registration);
        assert!(b.binary.is_none());
        assert!(cfg.bridges["gmessages"].enabled);
        assert!(cfg.bridges["slack"].enabled);
        assert!(!cfg.bridges["imessage"].enabled);
        assert_eq!(cfg.data_dir, dir.path().join("data"));
        // Tuwunel binds loopback only.
        let t = crate::homeserver::tuwunel_config(&cfg, b, "tok");
        let parsed: toml::Table = toml::from_str(&t).unwrap();
        assert_eq!(parsed["global"]["address"][0].as_str(), Some("127.0.0.1"));
        assert_eq!(parsed["global"]["allow_federation"].as_bool(), Some(false));
        // Embedded manifests were written and load.
        let ms = Manifest::load_dir(&paths.manifests()).unwrap();
        assert_eq!(ms.len(), EMBEDDED_MANIFESTS.len());
    }

    #[test]
    fn existing_config_is_kept_and_owner_becomes_admin() {
        let dir = tempfile::tempdir().unwrap();
        let paths = LocalPaths::new(dir.path());
        let opts = LocalOptions {
            bridges: vec![],
            ..Default::default()
        };
        prepare(&paths, &opts).unwrap();
        let edited = std::fs::read_to_string(paths.config()).unwrap().replace(
            "[bridges.groupme]\nenabled = false",
            "[bridges.groupme]\nenabled = true",
        );
        std::fs::write(paths.config(), edited).unwrap();
        LocalState {
            owner: Some("@devon:localhost".into()),
            created_at_ms: Some(1),
        }
        .save(&paths.state())
        .unwrap();
        let cfg = prepare(&paths, &LocalOptions::default()).unwrap();
        assert!(cfg.bridges["groupme"].enabled, "user edits survive");
        assert!(!cfg.bridges["slack"].enabled, "not regenerated");
        assert_eq!(cfg.auth.admins, vec!["@devon:localhost".to_string()]);
    }

    #[test]
    fn rejects_federated_local_config() {
        let dir = tempfile::tempdir().unwrap();
        let paths = LocalPaths::new(dir.path());
        std::fs::create_dir_all(dir.path()).unwrap();
        std::fs::write(
            paths.config(),
            default_config_toml(&LocalOptions::default())
                .replace("federation = false", "federation = true"),
        )
        .unwrap();
        assert!(prepare(&paths, &LocalOptions::default()).is_err());
    }

    #[test]
    fn localpart_and_password_rules() {
        assert!(validate_localpart("devon").is_ok());
        assert!(validate_localpart("d.k_1=x/y-z").is_ok());
        assert!(validate_localpart("").is_err());
        assert!(validate_localpart("Devon").is_err());
        assert!(validate_localpart("dev on").is_err());
        assert!(validate_localpart("devon:localhost").is_err());
        assert!(validate_password("short").is_err());
        assert!(validate_password("long enough").is_ok());
    }
}
