// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `kind_str`, `msg`, `on_rt`, `room`, `runtime`, `session_info`, `simple`, `slot`

/// Check that a URL is a Matrix homeserver; returns spec versions.
Future<List<String>> probeHomeserver({required String url}) =>
    RustLib.instance.api.crateApiMatrixProbeHomeserver(url: url);

Future<SessionInfo?> restoreSession({required String dataDir}) =>
    RustLib.instance.api.crateApiMatrixRestoreSession(dataDir: dataDir);

Future<SessionInfo> login({
  required String homeserver,
  required String username,
  required String password,
  required String dataDir,
  required String deviceName,
}) => RustLib.instance.api.crateApiMatrixLogin(
  homeserver: homeserver,
  username: username,
  password: password,
  dataDir: dataDir,
  deviceName: deviceName,
);

/// Stream of core updates. Starts the background sync loop.
Stream<CoreUpdate> subscribeUpdates() =>
    RustLib.instance.api.crateApiMatrixSubscribeUpdates();

Future<void> syncOnce() => RustLib.instance.api.crateApiMatrixSyncOnce();

Future<List<ChatRoom>> listRooms() =>
    RustLib.instance.api.crateApiMatrixListRooms();

Future<List<ChatMessage>> roomTimeline({
  required String roomId,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixRoomTimeline(
  roomId: roomId,
  limit: limit,
);

Future<List<ChatMessage>> threadTimeline({
  required String roomId,
  required String rootId,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixThreadTimeline(
  roomId: roomId,
  rootId: rootId,
  limit: limit,
);

Future<String> sendText({
  required String roomId,
  required String body,
  String? threadRoot,
}) => RustLib.instance.api.crateApiMatrixSendText(
  roomId: roomId,
  body: body,
  threadRoot: threadRoot,
);

/// Add or remove the user's reaction `key` on `event_id`: adding sends an
/// `m.reaction` annotation, removing redacts the user's own reaction(s).
/// Returns whether anything changed.
Future<bool> setReaction({
  required String roomId,
  required String eventId,
  required String key,
  required bool add,
}) => RustLib.instance.api.crateApiMatrixSetReaction(
  roomId: roomId,
  eventId: eventId,
  key: key,
  add: add,
);

/// One message by id (for the Saved list); `None` if it isn't a message.
Future<ChatMessage?> getMessage({
  required String roomId,
  required String eventId,
}) => RustLib.instance.api.crateApiMatrixGetMessage(
  roomId: roomId,
  eventId: eventId,
);

/// Mark a room read up to `event_id` (default: its latest message): read
/// receipt + fully-read marker, clears marked-unread. Returns the event id.
Future<String?> markRead({required String roomId, String? eventId}) => RustLib
    .instance
    .api
    .crateApiMatrixMarkRead(roomId: roomId, eventId: eventId);

/// Set / clear the room's marked-unread flag.
Future<void> setMarkedUnread({required String roomId, required bool unread}) =>
    RustLib.instance.api.crateApiMatrixSetMarkedUnread(
      roomId: roomId,
      unread: unread,
    );

/// The user's global account data of `event_type` as JSON, or None.
Future<String?> getAccountData({required String eventType}) =>
    RustLib.instance.api.crateApiMatrixGetAccountData(eventType: eventType);

/// Replace the user's global account data of `event_type` (a JSON object).
Future<void> setAccountData({
  required String eventType,
  required String json,
}) => RustLib.instance.api.crateApiMatrixSetAccountData(
  eventType: eventType,
  json: json,
);

/// Bytes of an attachment (decrypted) or avatar. `source` is
/// `ChatMedia::source` / `thumbnail_source` or an `mxc://` URL; with a size,
/// a server thumbnail is requested where possible.
Future<Uint8List> mediaBytes({
  required String source,
  int? thumbWidth,
  int? thumbHeight,
}) => RustLib.instance.api.crateApiMatrixMediaBytes(
  source: source,
  thumbWidth: thumbWidth,
  thumbHeight: thumbHeight,
);

Future<List<DirectoryUser>> searchDirectory({
  required String term,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixSearchDirectory(
  term: term,
  limit: limit,
);

Future<String> createDm({required String userId}) =>
    RustLib.instance.api.crateApiMatrixCreateDm(userId: userId);

Future<String> createGroup({
  required String name,
  required List<String> invites,
}) => RustLib.instance.api.crateApiMatrixCreateGroup(
  name: name,
  invites: invites,
);

Future<String> joinRoom({required String roomIdOrAlias}) =>
    RustLib.instance.api.crateApiMatrixJoinRoom(roomIdOrAlias: roomIdOrAlias);

Future<void> logout() => RustLib.instance.api.crateApiMatrixLogout();

/// Attachment; pass `source` to [`media_bytes`].
class ChatMedia {
  final String source;
  final String? mimetype;
  final BigInt? size;
  final int? width;
  final int? height;
  final BigInt? durationMs;
  final String filename;
  final String? caption;
  final String? thumbnailSource;

  const ChatMedia({
    required this.source,
    this.mimetype,
    this.size,
    this.width,
    this.height,
    this.durationMs,
    required this.filename,
    this.caption,
    this.thumbnailSource,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      mimetype.hashCode ^
      size.hashCode ^
      width.hashCode ^
      height.hashCode ^
      durationMs.hashCode ^
      filename.hashCode ^
      caption.hashCode ^
      thumbnailSource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMedia &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          mimetype == other.mimetype &&
          size == other.size &&
          width == other.width &&
          height == other.height &&
          durationMs == other.durationMs &&
          filename == other.filename &&
          caption == other.caption &&
          thumbnailSource == other.thumbnailSource;
}

class ChatMessage {
  final String eventId;
  final String sender;
  final String senderName;
  final String body;

  /// `text`, `notice`, `emote`, `image`, `file`, `video`, `audio`,
  /// `sticker`, `undecryptable`, `redacted`, `other`.
  final String kind;
  final PlatformInt64 ts;
  final String? threadRoot;
  final String? inReplyTo;
  final ThreadInfo? thread;
  final bool edited;
  final bool isOwn;

  /// `mxc://` avatar of the sender in this room.
  final String? senderAvatar;
  final ChatMedia? media;
  final List<ChatReaction> reactions;
  final ChatTapback? tapback;

  const ChatMessage({
    required this.eventId,
    required this.sender,
    required this.senderName,
    required this.body,
    required this.kind,
    required this.ts,
    this.threadRoot,
    this.inReplyTo,
    this.thread,
    required this.edited,
    required this.isOwn,
    this.senderAvatar,
    this.media,
    required this.reactions,
    this.tapback,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      sender.hashCode ^
      senderName.hashCode ^
      body.hashCode ^
      kind.hashCode ^
      ts.hashCode ^
      threadRoot.hashCode ^
      inReplyTo.hashCode ^
      thread.hashCode ^
      edited.hashCode ^
      isOwn.hashCode ^
      senderAvatar.hashCode ^
      media.hashCode ^
      reactions.hashCode ^
      tapback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sender == other.sender &&
          senderName == other.senderName &&
          body == other.body &&
          kind == other.kind &&
          ts == other.ts &&
          threadRoot == other.threadRoot &&
          inReplyTo == other.inReplyTo &&
          thread == other.thread &&
          edited == other.edited &&
          isOwn == other.isOwn &&
          senderAvatar == other.senderAvatar &&
          media == other.media &&
          reactions == other.reactions &&
          tapback == other.tapback;
}

class ChatReaction {
  final String key;
  final List<String> senders;
  final bool own;

  const ChatReaction({
    required this.key,
    required this.senders,
    required this.own,
  });

  @override
  int get hashCode => key.hashCode ^ senders.hashCode ^ own.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatReaction &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          senders == other.senders &&
          own == other.own;
}

class ChatRoom {
  final String roomId;
  final String name;
  final String? topic;
  final bool isDm;
  final BigInt unread;
  final BigInt highlights;
  final PlatformInt64 lastTs;
  final String? lastMessage;
  final String? networkId;
  final String? networkName;
  final bool? threadsSupported;

  /// Bridge identity, for grouping chats per bridge login (see
  /// `crosschat_core::NetworkInfo`).
  final String? bridgeId;
  final String? bridgeBot;
  final String? protocolId;
  final String? protocolName;
  final String? loginId;
  final String? roomType;

  /// `m.marked_unread` / `com.famedly.marked_unread`.
  final bool markedUnread;

  const ChatRoom({
    required this.roomId,
    required this.name,
    this.topic,
    required this.isDm,
    required this.unread,
    required this.highlights,
    required this.lastTs,
    this.lastMessage,
    this.networkId,
    this.networkName,
    this.threadsSupported,
    this.bridgeId,
    this.bridgeBot,
    this.protocolId,
    this.protocolName,
    this.loginId,
    this.roomType,
    required this.markedUnread,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      name.hashCode ^
      topic.hashCode ^
      isDm.hashCode ^
      unread.hashCode ^
      highlights.hashCode ^
      lastTs.hashCode ^
      lastMessage.hashCode ^
      networkId.hashCode ^
      networkName.hashCode ^
      threadsSupported.hashCode ^
      bridgeId.hashCode ^
      bridgeBot.hashCode ^
      protocolId.hashCode ^
      protocolName.hashCode ^
      loginId.hashCode ^
      roomType.hashCode ^
      markedUnread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatRoom &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name &&
          topic == other.topic &&
          isDm == other.isDm &&
          unread == other.unread &&
          highlights == other.highlights &&
          lastTs == other.lastTs &&
          lastMessage == other.lastMessage &&
          networkId == other.networkId &&
          networkName == other.networkName &&
          threadsSupported == other.threadsSupported &&
          bridgeId == other.bridgeId &&
          bridgeBot == other.bridgeBot &&
          protocolId == other.protocolId &&
          protocolName == other.protocolName &&
          loginId == other.loginId &&
          roomType == other.roomType &&
          markedUnread == other.markedUnread;
}

/// SMS/RCS tapback fallback text ("Loved “…”"), see `crosschat_core::Tapback`.
class ChatTapback {
  final String key;
  final bool removed;
  final String? targetText;
  final bool truncated;
  final String? targetKind;

  const ChatTapback({
    required this.key,
    required this.removed,
    this.targetText,
    required this.truncated,
    this.targetKind,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      removed.hashCode ^
      targetText.hashCode ^
      truncated.hashCode ^
      targetKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatTapback &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          removed == other.removed &&
          targetText == other.targetText &&
          truncated == other.truncated &&
          targetKind == other.targetKind;
}

/// Update pushed from the sync loop. `kind` is `rooms_changed`,
/// `new_message` (with `room_id` + `message`), `timeline_changed` (with
/// `room_id`: reactions, edits, redactions, member names changed) or
/// `sync_state` (with `state`).
/// A flat struct keeps the generated Dart free of code-gen dependencies.
class CoreUpdate {
  final String kind;
  final String? roomId;
  final ChatMessage? message;
  final String? state;

  const CoreUpdate({required this.kind, this.roomId, this.message, this.state});

  @override
  int get hashCode =>
      kind.hashCode ^ roomId.hashCode ^ message.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreUpdate &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          roomId == other.roomId &&
          message == other.message &&
          state == other.state;
}

class DirectoryUser {
  final String userId;
  final String? displayName;

  const DirectoryUser({required this.userId, this.displayName});

  @override
  int get hashCode => userId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectoryUser &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName;
}

class SessionInfo {
  final String userId;
  final String deviceId;
  final String homeserver;
  final String accessToken;

  const SessionInfo({
    required this.userId,
    required this.deviceId,
    required this.homeserver,
    required this.accessToken,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      deviceId.hashCode ^
      homeserver.hashCode ^
      accessToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionInfo &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          homeserver == other.homeserver &&
          accessToken == other.accessToken;
}

class ThreadInfo {
  final int replyCount;
  final PlatformInt64? latestReplyTs;
  final String? latestReplyBody;
  final List<String> participants;

  const ThreadInfo({
    required this.replyCount,
    this.latestReplyTs,
    this.latestReplyBody,
    required this.participants,
  });

  @override
  int get hashCode =>
      replyCount.hashCode ^
      latestReplyTs.hashCode ^
      latestReplyBody.hashCode ^
      participants.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadInfo &&
          runtimeType == other.runtimeType &&
          replyCount == other.replyCount &&
          latestReplyTs == other.latestReplyTs &&
          latestReplyBody == other.latestReplyBody &&
          participants == other.participants;
}
