// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `kind_str`, `msg`, `on_rt`, `room`, `runtime`, `session_info`, `simple`, `slot`

/// Check that a URL is a Matrix homeserver; returns spec versions.
Future<List<String>> probeHomeserver({required String url}) =>
    RustLib.instance.api.crateApiMatrixProbeHomeserver(url: url);

Future<SessionInfo?> restoreSession({required String dataDir}) =>
    RustLib.instance.api.crateApiMatrixRestoreSession(dataDir: dataDir);

Future<SessionInfo> login({
  required String homeserver,
  required String username,
  required String password,
  required String dataDir,
  required String deviceName,
}) => RustLib.instance.api.crateApiMatrixLogin(
  homeserver: homeserver,
  username: username,
  password: password,
  dataDir: dataDir,
  deviceName: deviceName,
);

/// Stream of core updates. Starts the background sync loop.
Stream<CoreUpdate> subscribeUpdates() =>
    RustLib.instance.api.crateApiMatrixSubscribeUpdates();

Future<void> syncOnce() => RustLib.instance.api.crateApiMatrixSyncOnce();

Future<List<ChatRoom>> listRooms() =>
    RustLib.instance.api.crateApiMatrixListRooms();

Future<List<ChatMessage>> roomTimeline({
  required String roomId,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixRoomTimeline(
  roomId: roomId,
  limit: limit,
);

Future<List<ChatMessage>> threadTimeline({
  required String roomId,
  required String rootId,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixThreadTimeline(
  roomId: roomId,
  rootId: rootId,
  limit: limit,
);

Future<String> sendText({
  required String roomId,
  required String body,
  String? threadRoot,
}) => RustLib.instance.api.crateApiMatrixSendText(
  roomId: roomId,
  body: body,
  threadRoot: threadRoot,
);

Future<List<DirectoryUser>> searchDirectory({
  required String term,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixSearchDirectory(
  term: term,
  limit: limit,
);

Future<String> createDm({required String userId}) =>
    RustLib.instance.api.crateApiMatrixCreateDm(userId: userId);

Future<String> createGroup({
  required String name,
  required List<String> invites,
}) => RustLib.instance.api.crateApiMatrixCreateGroup(
  name: name,
  invites: invites,
);

Future<String> joinRoom({required String roomIdOrAlias}) =>
    RustLib.instance.api.crateApiMatrixJoinRoom(roomIdOrAlias: roomIdOrAlias);

Future<void> logout() => RustLib.instance.api.crateApiMatrixLogout();

class ChatMessage {
  final String eventId;
  final String sender;
  final String senderName;
  final String body;

  /// `text`, `notice`, `emote`, `image`, `file`, `video`, `audio`,
  /// `sticker`, `undecryptable`, `redacted`, `other`.
  final String kind;
  final PlatformInt64 ts;
  final String? threadRoot;
  final String? inReplyTo;
  final ThreadInfo? thread;
  final bool edited;
  final bool isOwn;

  const ChatMessage({
    required this.eventId,
    required this.sender,
    required this.senderName,
    required this.body,
    required this.kind,
    required this.ts,
    this.threadRoot,
    this.inReplyTo,
    this.thread,
    required this.edited,
    required this.isOwn,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      sender.hashCode ^
      senderName.hashCode ^
      body.hashCode ^
      kind.hashCode ^
      ts.hashCode ^
      threadRoot.hashCode ^
      inReplyTo.hashCode ^
      thread.hashCode ^
      edited.hashCode ^
      isOwn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sender == other.sender &&
          senderName == other.senderName &&
          body == other.body &&
          kind == other.kind &&
          ts == other.ts &&
          threadRoot == other.threadRoot &&
          inReplyTo == other.inReplyTo &&
          thread == other.thread &&
          edited == other.edited &&
          isOwn == other.isOwn;
}

class ChatRoom {
  final String roomId;
  final String name;
  final String? topic;
  final bool isDm;
  final BigInt unread;
  final BigInt highlights;
  final PlatformInt64 lastTs;
  final String? lastMessage;
  final String? networkId;
  final String? networkName;
  final bool? threadsSupported;

  /// Bridge identity, for grouping chats per bridge login (see
  /// `crosschat_core::NetworkInfo`).
  final String? bridgeId;
  final String? bridgeBot;
  final String? protocolId;
  final String? protocolName;
  final String? loginId;
  final String? roomType;

  const ChatRoom({
    required this.roomId,
    required this.name,
    this.topic,
    required this.isDm,
    required this.unread,
    required this.highlights,
    required this.lastTs,
    this.lastMessage,
    this.networkId,
    this.networkName,
    this.threadsSupported,
    this.bridgeId,
    this.bridgeBot,
    this.protocolId,
    this.protocolName,
    this.loginId,
    this.roomType,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      name.hashCode ^
      topic.hashCode ^
      isDm.hashCode ^
      unread.hashCode ^
      highlights.hashCode ^
      lastTs.hashCode ^
      lastMessage.hashCode ^
      networkId.hashCode ^
      networkName.hashCode ^
      threadsSupported.hashCode ^
      bridgeId.hashCode ^
      bridgeBot.hashCode ^
      protocolId.hashCode ^
      protocolName.hashCode ^
      loginId.hashCode ^
      roomType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatRoom &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name &&
          topic == other.topic &&
          isDm == other.isDm &&
          unread == other.unread &&
          highlights == other.highlights &&
          lastTs == other.lastTs &&
          lastMessage == other.lastMessage &&
          networkId == other.networkId &&
          networkName == other.networkName &&
          threadsSupported == other.threadsSupported &&
          bridgeId == other.bridgeId &&
          bridgeBot == other.bridgeBot &&
          protocolId == other.protocolId &&
          protocolName == other.protocolName &&
          loginId == other.loginId &&
          roomType == other.roomType;
}

/// Update pushed from the sync loop. `kind` is `rooms_changed`,
/// `new_message` (with `room_id` + `message`) or `sync_state` (with `state`).
/// A flat struct keeps the generated Dart free of code-gen dependencies.
class CoreUpdate {
  final String kind;
  final String? roomId;
  final ChatMessage? message;
  final String? state;

  const CoreUpdate({required this.kind, this.roomId, this.message, this.state});

  @override
  int get hashCode =>
      kind.hashCode ^ roomId.hashCode ^ message.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreUpdate &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          roomId == other.roomId &&
          message == other.message &&
          state == other.state;
}

class DirectoryUser {
  final String userId;
  final String? displayName;

  const DirectoryUser({required this.userId, this.displayName});

  @override
  int get hashCode => userId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectoryUser &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName;
}

class SessionInfo {
  final String userId;
  final String deviceId;
  final String homeserver;
  final String accessToken;

  const SessionInfo({
    required this.userId,
    required this.deviceId,
    required this.homeserver,
    required this.accessToken,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      deviceId.hashCode ^
      homeserver.hashCode ^
      accessToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionInfo &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          homeserver == other.homeserver &&
          accessToken == other.accessToken;
}

class ThreadInfo {
  final int replyCount;
  final PlatformInt64? latestReplyTs;
  final String? latestReplyBody;
  final List<String> participants;

  const ThreadInfo({
    required this.replyCount,
    this.latestReplyTs,
    this.latestReplyBody,
    required this.participants,
  });

  @override
  int get hashCode =>
      replyCount.hashCode ^
      latestReplyTs.hashCode ^
      latestReplyBody.hashCode ^
      participants.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadInfo &&
          runtimeType == other.runtimeType &&
          replyCount == other.replyCount &&
          latestReplyTs == other.latestReplyTs &&
          latestReplyBody == other.latestReplyBody &&
          participants == other.participants;
}
